### ISSUE TITLE
Improved cloud-watch alarm naming via suffix

### ISSUE THREAD

**Issue by exequielrafaela** [trussworks/terraform-aws-root-login-notifications#5]
Having the possibility to optionally add a suffix to the cloudwatch alarm name:  `iam-root-login-alarm` by using a variable would be very useful in order to identify from which AWS Account we're receiving the alarm.

In our example you can see that both Alarms from different sources: AWS Account A & AWS Account B result in the exact same alarm in our Slack Channel, even `Link to Alarm` is equal (which will redirect you to the current AWS Account Web Console you're logged in).
 
![image](https://user-images.githubusercontent.com/18539704/73648322-16b33400-465c-11ea-925b-d513e980898d.png)

Not sure if I'm missing something here. Hope you find this enhancement to be functional for a Multi-Account AWS Organization configuration as we do.

Thanks in advance! 

CC: @diego-ojeda-binbash @mpagnucco @AlfredoPardo @gdmlnx

**Comment by mr337** [comment]
Hi @exequielrafaela, we just released https://github.com/trussworks/terraform-aws-root-login-notifications/releases/tag/v2.1.1. This allows updating the CW alarm name for seeing where the alarm originated from. 

At the moment we don't have an easy fix for the URL the alarm provides. This is generated from CW directly and this module simply passes that along. One option @esacteksab recommended is https://aws.amazon.com/blogs/mt/monitor-and-notify-on-aws-account-root-user-activity/ which involves another lambda.

**Comment by exequielrafaela** [comment]
@mr337 I think that the suffix brings a great solution here :) 

```
 ~ alarm_name = "iam-root-login-alarm" -> "iam-root-login-alarm-523XXXXXXXXX" # forces replacement
```

![image](https://user-images.githubusercontent.com/18539704/73746736-a62c1600-4734-11ea-9e51-e94abba946fe.png)

The URL fix would not be strictly necessary considering from now on we can easily identify via the CW alarm name which was the 'Root Loging Alert' originating account.

Thanks a lot for your collab here, from our side we consider this issue as **resolved** :+1: :heavy_check_mark: :checkered_flag:

**Comment by mr337** [comment]
Appreciate the feedback, closing for now.
